version: "2"
services:
  aria2:
    image: almir1904/docker-qbittorrent-enhanced
    container_name: qbittorrent-enhanced
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Europe/Vienna
    volumes:
      - /path/to/appdata/config:/config
      - /path/to/downloads:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080
    restart: unless-stopped
