name: Check and Update ReleaseTag

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      manual_trigger:
        description: 'Manually trigger the workflow'
        default: 'false'
        required: false

jobs:
  update_release_tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Get latest release from linked repository
        id: latest_release
        run: |
          release_url="https://api.github.com/repos/c0re100/qBittorrent-Enhanced-Edition/releases/latest"
          latest_release=$(curl -s $release_url | jq -r .tag_name)
          latest_release=${latest_release#release-}  # Remove "release-" prefix
          echo "Latest release from API: $latest_release"
          echo "Latest_Release=$latest_release" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Read current ReleaseTag file
        id: read_release_tag
        run: |
          release_tag=$(cat ReleaseTag)
          echo "Current Release: $release_tag"
           echo "ReleaseTag=$release_tag" >> $GITHUB_ENV
        
      - name: Compare releases and update ReleaseTag
        if: ${{ env.ReleaseTag }} != ${{ env.LatestRelease }}
        run: |
          echo "Updating ReleaseTag file"
          echo ${{ env.LatestRelease }} > ReleaseTag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Commit and push if ReleaseTag was updated
        if: ${{ env.ReleaseTag }} != ${{ env.LatestRelease }}
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add ReleaseTag
          git commit -m "Update ReleaseTag to ${{ env.LatestRelease }}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
