name: Publish Docker image

on: push

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4.1.7
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3.2.0
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          
      - name: Log in to Github
        uses: docker/login-action@v3.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GIT_TOKEN }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: |
           almir1904/docker-qbittorrent-enhanced
           ghcr.io/${{ github.repository }}
          
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.1.0
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3.4.0

      - name: Build and push Docker image AMD64
        uses: docker/build-push-action@v6.3.0
        with:
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          platforms: linux/amd64
          tags: |
            almir1904/docker-qbittorrent-enhanced:latest
            ghcr.io/almir1904/docker-qbittorrent-enhanced:latest
          labels: ${{ steps.meta.outputs.labels }}
